version: "3.5"
services:
  db:
    image: postgres:11
    restart: always
    container_name: db_app
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb/10-init.sql
      - .:/docker-entrypoint-initdb.d
    env_file:
      - .env-prod
  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    command: ["/fastapi_app/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
