version: "3.7"
services:
  db:
    image: postgres:11
    container_name: db_app
    command:
      - p 5433
    expose:
      - 5433
    env_file:
      - .env-prod
  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: fastapi_app
    ports:
      - 9999:8000
    depends_on:
      - db
