"""Database creation

Revision ID: f905e875d911
Revises: 
Create Date: 2023-11-05 20:09:25.272255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f905e875d911'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, unique=True, comment='Уникальный идентификатор'),
                    sa.Column('courier_name', sa.String(), nullable=False, comment='Имя курьера'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table_comment('couriers', 'Таблица курьеров')
    op.create_table('regions',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, unique=True, comment='Уникальный идентификатор'),
                    sa.Column('region_name', sa.String(), nullable=False, comment='Наименование региона'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table_comment('regions', 'Таблица регионов')
    op.create_table('courier_region',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, unique=True, comment='Уникальный идентификатор'),
                    sa.Column('courier_id', sa.Integer(), nullable=False, comment='Внешний ключ на courier.id'),
                    sa.Column('region_id', sa.Integer(), nullable=False, comment='Внешний ключ на region.id'),
                    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.PrimaryKeyConstraint('id', 'courier_id', 'region_id')
                    )
    op.create_table_comment('courier_region', 'Расшивочная таблица для связи курьеров и регионов')
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, unique=True, comment='Уникальный идентификатор'),
                    sa.Column('courier_id', sa.Integer(), nullable=False, comment='Внешний ключ на courier.id'),
                    sa.Column('region_id', sa.Integer(), nullable=False, comment='Внешний ключ на region.id'),
                    sa.Column('order_text', sa.String(), nullable=False, comment='Текст заказа'),
                    sa.Column('start_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False, comment='Время регистрации заказа'),
                    sa.Column('finish_time', sa.TIMESTAMP(timezone=True), nullable=True, comment='Время завершения заказа'),
                    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.PrimaryKeyConstraint('id', 'courier_id', 'region_id')
                    )
    op.create_table_comment('orders', 'Таблица заказов')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('courier_region')
    op.drop_table('regions')
    op.drop_table('couriers')
    # ### end Alembic commands ###
